#! /bin/sh
setxkbmap de
exec polybar workspaces &
exec polybar status &
exec nitrogen --restore &
exec picom &
exec xbanish &
xbindkeys

wget -q --spider http://duckduckgo.org
if [ $? -eq 0 ]; then
    exec polybar top &
else
    notify-send "No Internet connection"
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#81a1c1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=fullscreen
